[options]
addons_path = /usr/lib/python3/dist-packages/odoo/addons
data_dir = /var/lib/odoo
proxy_mode = True

; إعدادات قاعدة البيانات المحقونة برمجياً
db_host = dpg-d8n62tjtqb8s73cqdmu0-a
db_user = odoo_user
db_password = thyx8PUOAyjMNxbh8stJl9AT38v8Q4AS
database = odoo_em2k
db_port = 5432

; تعيين الماستر باسورد لتخطي شاشة التهيئة المكسورة
admin_passwd = thyx8PUOAyjMNxbh8stJl9AT38v8Q4AS
